###
GET http://localhost:3000/api/sets

###
GET http://localhost:3000/api/sets/1

###
POST http://localhost:3000/api/sets
Content-Type: application/json

{
  "name": "New set",
  "release": 2010,
  "parts": 396,
  "theme": "Star Wars"
}

###
PUT http://localhost:3000/api/sets/1
Content-Type: application/json

{
  "name": "Updated set",
  "release": 2010,
  "parts": 396,
  "theme": "Star Wars"
}

###
DELETE http://localhost:3000/api/sets/1

