POST http://localhost:3000/api/sets
Content-Type: application/json

{
  "name": "New set",
  "release": 2020,
  "parts": 1000,
  "theme": "Star Wars"
}

###
GET http://localhost:3000/api/sets/1
Accept: application/json

###
GET http://localhost:3000/api/sets
Accept: application/json

###
PUT http://localhost:3000/api/sets/1
Content-Type: application/json

{
  "name": "Updated set",
  "release": 2020,
  "parts": 1000,
  "theme": "Star Wars"
}

###
DELETE http://localhost:3000/api/sets/1
Accept: application/json


